# config.yml
banknotes:
  500: 34
  200: 34
  100: 34
  50: 34
  20: 34
  10: 34
  5: 34
  2: 34
  1: 34
accounts:
  3321:
    name: 'Volodymyr'
    password: 'mypass'
    balance: 422
  5922:
    name: 'Iryna'
    password: 'mypass'
    balance: 5301